# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.14.0]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deployment to multiple hosts with different ports
        uses: ./
        with:
          host: "${{ secrets.HOST }}:${{ secrets.PORT }}"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 8899
          script_stop: true
          script: |
              ls \
                -lah
          use_insecure_cipher: true
